---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    url: ${GIT_REPO_URL}
    token: ${GIT_REPO_TOKEN}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: DEV
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy to Dev
    type: deployer
    target:
      region_id: ${DEV_REGION_ID}
      organization: ${DEV_ORG_NAME}
      space: ${DEV_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      cf create-service DataCache starter otc-setup-ui-cache
      # Push app
      export CF_APP_NAME="dev-$CF_APP"
      cf push "${CF_APP_NAME}" c null --no-start
      cf set-env "${CF_APP_NAME}" BLUEMIX_APP_MGMT_ENABLE devconsole+shell+inspector
      cf set-env "${CF_APP_NAME}" NODE_ENV development
      cf start "${CF_APP_NAME}"
      export APP_URL=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      # View logs
      #cf logs "${CF_APP_NAME}" --recent

